### PR TITLE
support php8

### LINKED ISSUE #3: Support PHP 8
PHP constraint to PHP 7.1 restrict the use of PHP 8
Could this be changed (if the codebase is deemed compatible)

### PR DESCRIPTION
**Pull request by drzraf**
fix #3

### CODE REVIEW

**Comment by Ayesh** [comment]
Awesome, thanks a lot!

**Comment by drzraf** [comment]
tagged release?

**Comment by drzraf** [comment]
ping :)

**Comment by drzraf** [comment]
ping

**Pull request merged**
